### ISSUE TITLE
serialization format for storing analysis

### ISSUE THREAD

**Issue by jkanche** [jkanche/kana#25]
- [x] Converter from TypedArray to JSON arrays (handled by #34).
- [x] Figure out IndexedDB/inline file format (#57)
- [x] transfer serialized buffer to main thread (handled by #34).
- [x] Adapt options to be able to load state or from IndexedDB (#57)
- [x] Fix bugs with serialization code (handled by #34).
- [x] Fix bugs with unserialization code. (#44)
- [x] UI changes to save/load various formats (#43)
