### ISSUE TITLE
Support input formats

### ISSUE THREAD

**Issue by jkanche** [jkanche/kana#26]
- [x] Get HDF5 to work (https://github.com/jkanche/kana/pull/31)
- [x] UI support for choosing various formats (#46)
- [x] Figure out how uses can choose between different input formats (#57)
- [x] Autofill state when loading existing analysis (#57)
- [x] validating input files based on extensions (https://github.com/jkanche/kana/pull/36)
