### ISSUE TITLE
Gene names and symbols

### ISSUE THREAD

**Issue by jkanche** [jkanche/kana#27]
- [x] Figure out gene names/symbols #52)
- [x] main thread owns gene names (#38).
- [x] handle gzipped files (#34).
- [x] hardcode human and mouse mitochondrial genes (#40 -> #48)
  - [x]  UI to support use hardcoded one or provide a regex
