### ISSUE TITLE
aesthetics

### ISSUE THREAD

**Issue by jkanche** [jkanche/kana#28]
- [x] Animations for t-SNE/UMAP (#39)
- [x] sliders histogram changes to gradient (#50)
- [x] save tsne to gallery (#49)
- [x] change qc plot ticks to normal text (#50)
- [x] send dims in the data payloads (#50)
- [x] filter markers set default to 0 for lfc and delta-d (#50)
- [ ] Fancier would be to save and restore the state from gallery
- [ ] change the pong game to conways game of life

**Comment by jkanche** [comment]
#92
